#!/bin/bash

function questa {
    vlib work && \
    vlog \
        +incdir+../../+../../uvm_unit-uvm-1.2/src \
        -R \
            -c \
            -sv_lib $UVM_LIB \
            -do "run -all; quit -f" \
        - \
        $*
    rm -rf transcript work
}

questa my_property_test.sv
