#!/bin/bash

function incisiv {
    irun                                    \
        -sv                                 \
        -uvmhome ../../uvm_unit-uvm-1.2     \
        -uvmnoautocompile                   \
        -uvmnocdnsextra                     \
        -uvmnoloaddpi                       \
        -sv_lib $UVM_LIB                    \
        -incdir ../../                      \
        -incdir ../../uvm_unit-uvm-1.2/src  \
        $*
        rm -rf INCA_libs irun.history irun.log
}

incisiv checker_test.sv

